# state length:
STATE_SIZE = 93

# state indices:
NEXT_SYMBOL_STATE_INDEX = 90
CONSTRAINT_STATE_INDEX = 91
UTTT_RESULT_STATE_INDEX = 92

# state values:
X_STATE_VALUE = 1
O_STATE_VALUE = 2
DRAW_STATE_VALUE = 3
UNCONSTRAINED_STATE_VALUE = 9
